const playerData = [
    {
        id: 1,
        imageURL: 'https://cdn3.mozzartsport.co.ke/upload/player/haland.png_1673701268443.png',
        playerPrice: 180,
        playerName: 'Erling Haaland',
        playerClub: 'Manchester City FC',
    },
    {
        id: 2,
        imageURL: 'https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhwYsnLbohTzOYVCCMVAaFMpKUYIqciFFc_tlZSZHrdhgfMDzeoWlfn3StEwyvOAt5VnEIAZOrWhHsCoam01bW8e0BjzV-Vv-jzrzWdCsP4uo1BVuf1xvMvdZaYHeGhKZ0QeYtDiO20Z4lTAhuPgN17W6YUFLqQsJ0vO0m94cU5Zkg5bkyBFqcf0qhC/s500/Rolnaldo.png',
        playerPrice: 15,
        playerName: 'Cristiano Ronaldo',
        playerClub: 'Al-Nassr FC',
    },
    {
        id: 3,
        imageURL: 'https://www.pngall.com/wp-content/uploads/13/Harry-Kane-PNG-Photo.png',
        playerPrice: 90,
        playerName: 'Harry Kane',
        playerClub: 'FC Bayern München',
    },
    {
        id: 4,
        imageURL: 'https://i.bundesliga.com/player/dfl-obj-0002f5-dfl-clu-00000g-dfl-sea-0001k7.png',
        playerPrice: 75,
        playerName: 'Joshua Kimmich',
        playerClub: 'FC Bayern München',
    },
    {
        id: 5,
        imageURL: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p171314.png',
        playerPrice: 105,
        playerName: 'Rúben Dias',
        playerClub: 'Manchester City FC',
    },
    {
        id: 6,
        imageURL: 'https://i.bundesliga.com/player/dfl-obj-0000ia-dfl-clu-00000g-dfl-sea-0001k7.png',
        playerPrice: 12,
        playerName: 'Thomas Müller',
        playerClub: 'FC Bayern München',
    },
    {
        id: 7,
        imageURL: 'https://resources.premierleague.com/premierleague/photos/players/250x250/p219847.png',
        playerPrice: 55,
        playerName: 'Kai Havertz',
        playerClub: 'Chelsea FC',
    },
    {
        id: 8,
        imageURL: 'https://parimatchnews.com/wp-content/uploads/2020/11/Van-Dijk.png',
        playerPrice: 35,
        playerName: 'Virgil Van Dijk',
        playerClub: 'Liverpool FC',
    },
    {
        id: 9,
        imageURL: 'https://www.mancity.com/meta/media/oelcevzg/nathan-ake-r.png',
        playerPrice: 42,
        playerName: 'Nathan Aké',
        playerClub: 'Manchester City',
    },
    {
        id: 10,
        imageURL: 'https://i.bundesliga.com/player/dfl-obj-002gcr-dfl-clu-00000g-dfl-sea-0001k7.png',
        playerPrice: 110,
        playerName: 'Jamal Musiala',
        playerClub: 'FC Bayern München',
    },
    {
        id: 11,
        imageURL: 'https://i.bundesliga.com/player/dfl-obj-j01k76-dfl-clu-00000b-dfl-sea-0001k7.png',
        playerPrice: 35,
        playerName: 'Piero Hincapié',
        playerClub: 'Bayer Leverkusen',
    },
    {
        id: 12,
        imageURL: 'https://www.mancity.com/meta/media/oj0hihqs/manuel-akanji.png',
        playerPrice: 38,
        playerName: 'Manuel Akanji',
        playerClub: 'Manchester City',
    },
    {
        id: 13,
        imageURL: 'https://i.bundesliga.com/player/dfl-obj-002ge9-dfl-clu-000007-dfl-sea-0001k7.png',
        playerPrice: 120,
        playerName: 'Jude Bellingham',
        playerClub: 'Real Madrid CF',
    },
    {
        id: 14,
        imageURL: 'https://assets.laliga.com/squad/2023/t178/p209712/2048x2048/p209712_t178_2023_0_003_000.png',
        playerPrice: 75,
        playerName: 'Frenkie de Jong',
        playerClub: 'FC barcelona',
    },
];

export default playerData;
